version: '3.9'

services:
  # agi:
  #   image: trueagi/hyperon

  ctx:
    image: ghcr.io/0-5788719150923125/ctx:latest
    restart: 'always'
    network_mode: host
    environment:
      ANONYMOUS: ${ANONYMOUS:-true}
    env_file:
      - .env

  uxo:
    image: ghcr.io/0-5788719150923125/uxo:latest
    network_mode: 'host'
    env_file:
      - .env

  tbd:
    image: ghcr.io/0-5788719150923125/lab:latest
    command: tensorboard --logdir /data/logs --bind_all --samples_per_plugin scalars=999999999
    volumes:
      - ./data:/data
    ports:
      - 6006:6006

  opt:
    image: ghcr.io/optuna/optuna-dashboard
    command: sqlite:////data/optuna.sqlite3
    volumes:
      - ./data:/data
    ports:
      - 6007:8080
    logging:
      driver: none

  pet:
    image: learningathome/petals:main
    command: python -m petals.cli.run_server TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T --public_name "https://src.eco" --cache_dir /data/models --num_blocks 4 --torch_dtype bfloat16
    restart: 'always'
    network_mode: 'host'
    ipc: host
    deploy:
      resources:
        limits:
          cpus: '0.1'
    volumes:
      - ./data/models:/data/models
      - ./data/adapters:/data/adapters
    environment:
      HIVEMIND_LOGLEVEL: ERROR

  pen:
    image: learningathome/petals:main
    command: python -m petals.cli.run_server bigscience/bloom-560m --public_name "https://src.eco" --cache_dir /data/models --num_blocks 10 --torch_dtype bfloat16
    restart: 'always'
    network_mode: 'host'
    ipc: host
    deploy:
      resources:
        limits:
          cpus: '0.1'
    volumes:
      - ./data/models:/data/models
      - ./data/adapters:/data/adapters
    environment:
      HIVEMIND_LOGLEVEL: ERROR

  ipf:
    image: ipfs/kubo:latest
    restart: 'always'
    command: daemon --init-profile=lowpower --migrate
    volumes:
      - ./book:/book
      - data:/data/ipfs

  urb:
    image: tloncorp/vere
    command: /bin/start-urbit --loom=29
    # restart: 'always'
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2GB
    volumes:
      - ./data/urbit:/urbit
    ports:
      - 9099:80
      - 34343:34343/udp

volumes:
  data: