version: '3.9'

services:
  # agi:
  #   image: trueagi/hyperon

  ctx:
    image: ghcr.io/0-5788719150923125/ctx:latest
    restart: 'always'
    network_mode: host
    environment:
      ANONYMOUS: ${ANONYMOUS:-true}
    env_file:
      - .env

  uxo:
    image: ghcr.io/0-5788719150923125/uxo:latest
    network_mode: 'host'
    env_file:
      - .env

  # tra:
  #   image: traefik:latest
  #   command:
  #     - "--api.insecure=true"
  #     - "--api.dashboard=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=true"
  #     - "--providers.docker.watch=true"
  #     - "--entrypoints.web.address=:80"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
  #     - "traefik.http.routers.traefik.service=api@internal"
  #   ports:
  #     - "8888:8080"
  #     - "8889:80"
  #     - "8890:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  tbd:
    image: ghcr.io/0-5788719150923125/lab:latest
    command: tensorboard --logdir /data/logs --bind_all --samples_per_plugin scalars=999999999
    volumes:
      - ./data:/data
    ports:
      - 8883:6006

  pet:
    image: learningathome/petals:main
    command: python -m petals.cli.run_server "bigscience/bloom-560m" --public_name "https://src.eco" --cache_dir /data/models --num_blocks 10 --torch_dtype bfloat16
    restart: 'always'
    network_mode: 'host'
    ipc: host
    deploy:
      resources:
        limits:
          cpus: '0.23'
    volumes:
      - ./data/models:/data/models
      - ./data/adapters:/data/adapters
    environment:
      HIVEMIND_LOGLEVEL: ERROR

  ipf:
    image: ipfs/kubo:latest
    restart: 'always'
    command: daemon --init-profile=lowpower --migrate
    volumes:
      - ./book:/book
      - data:/data/ipfs

  urb:
    image: tloncorp/vere
    command: /bin/start-urbit --loom=29
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2GB
    volumes:
      - ./data/urbit:/urbit
    ports:
      - 8885:80
      - 34343:34343/udp

volumes:
  data: