services:
  lab:
    # command: rocm-smi
    # command: /opt/rocm/bin/rocminfo
    build:
      args:
        ARCH: amd64
        SOURCE_IMAGE: rocm/pytorch:rocm5.7_ubuntu22.04_py3.10_pytorch_2.0.1
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
    # environment:
    #   - ROC_ENABLE_PRE_VEGA: "1"