version: '3.9'

services:
  lab:
    build:
      args:
        ARCH: amd64
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all