version: '3.9'

services:
  lab:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
        limits:
          cpus: '2.0'