version: '3.9'

services:
  pvt:
    image: tyrrrz/discordchatexporter:latest
    command: exportdm -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  src:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "830300981966143488" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  vtX:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "896111349300592650" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  lab:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "1041331166592106576" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  laB:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "907925566089465886" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  kun:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "747807102759731291" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  sev:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "1047276906636132432" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  bot:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "922565350598508664" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  pan:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "829345498326106142" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  dfw:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "976908406864613436" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab

  dfw:
    image: tyrrrz/discordchatexporter:latest
    command: exportguild --guild "840978732772753468" -t "${SELFTOKEN}" -o "/lab/texts/discord" -f "JSON"
    volumes:
      - ./lab:/lab
