version: '3.9'

services:
  lab:
    image: ghcr.io/0-5788719150923125/lab:latest
    restart: 'always'
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}.${DEVICE:-nvidia}
      shm_size: '1gb'
      args:
        DCE_VERSION: 2.42.3
        DOTNET_VERSION: 7.0.10
        HUGO_VERSION: 0.118.2
        NODEMON_VERSION: 3.0.1
        NODE_MAJOR_VERSION: 20
        WRANGLER_VERSION: 3.8.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      FOCUS: ${FOCUS:-toe}
      RAY_memory_monitor_refresh_ms: 0