version: '3.9'

services:
  vtx:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['1']

  ctx:
    environment:
      CHANNELS: 'hive,support,alpha,mars,opencog,microsoft,apple,openai,google,rock,eve,vtx,universe,prism,astral'
      WEBUI: enabled
