version: '3.9'

services:
  vtx:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  ctx:
    environment:
      CHANNELS: 'hive,support,opencog'
      WEBUI: enabled
