version: '3.9'

services:
  lab:
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${DEVICE:-nvidia}
              capabilities: [gpu]
        limits:
          cpus: '2.0'