version: '3.9'

services:
  vtx:
    image: ghcr.io/0-5788719150923125/src:1
    command: nodemon --ignore "models/*" --ignore "*.json" --exec python3 main.py
    restart: 'always'
    user: 1000:1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./lab:/lab
      - ./vtx:/vtx
    env_file:
      - .env
    environment:
      FOCUS: heart
      TRANSFORMERS_CACHE: /tmp

  ctx:
    image: ghcr.io/0-5788719150923125/src:1
    command: node root.js
    ports:
      - 9666:9665

  ips:
    image: ipfs/kubo:master-latest
    command: daemon --migrate=true --agent-version-suffix=docker --init-profile=lowpower --writable --enable-gc --enable-pubsub-experiment --enable-namesys-pubsub
