version: '3.9'

services:
  tb:
    image: ghcr.io/0-5788719150923125/bot:latest
    command: tensorboard --logdir /data/logs --bind_all --samples_per_plugin scalars=999999999
    volumes:
      - ./data:/data
    ports:
      - 6006:6006

  pet:
    image: learningathome/petals:main
    command: python -m petals.cli.run_server bigscience/bloom-560m --public_name "https://src.eco" --cache_dir /data/models --num_blocks 24 --torch_dtype bfloat16
    restart: 'always'
    network_mode: 'host'
    ipc: host
    deploy:
      resources:
        limits:
          cpus: '0.75'
    volumes:
      - ./data/models:/data/models
      - ./data/adapters:/data/adapters
    environment:
      HIVEMIND_LOGLEVEL: ERROR

  ipfs:
    image: ipfs/kubo:latest
    command: daemon --init-profile=lowpower
    ports:
      - 9090:8080
    volumes:
      - ./book:/book
      - data:/data/ipfs

  # port:
  #   image: tloncorp/vere:edge
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: 1GB
  #   ports:
  #     - 9090:80
  #     - 34343:34343/udp

volumes:
  data: