version: '3.9'

services:
  bot:
    image: ghcr.io/0-5788719150923125/bot:latest
    restart: 'always'
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile.${ARCH:-x64}
      shm_size: '1gb'
      args: 
        DCE_VERSION: 2.40.4
        DOTNET_VERSION: 7.0.10
        HUGO_VERSION: 0.118.2
        NODEMON_VERSION: 3.0.1
        NODE_MAJOR_VERSION: 20
        WRANGLER_VERSION: 3.8.0
    volumes:
      - ./book:/book
      - ./gen:/gen
      - ./lab:/lab
      - ./src:/src
    env_file:
      - .env
    environment:
      FOCUS: ${FOCUS:-heart}

  ctx:
    image: ghcr.io/0-5788719150923125/ctx:latest
    restart: 'always'
    network_mode: host