version: '3.9'

services:
  vtx:
    image: ghcr.io/0-5788719150923125/src:1
    command: nodemon --ext '*.py, *.yml' --ignore "models/*" --ignore "*.json" --exec python3 main.py
    restart: 'always'
    user: 1000:1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              # device_ids: ['0']
    ulimits:
      memlock: -1
      stack: 67108864
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    stdin_open: true
    tty: true
    volumes:
      - ./gen:/gen
      - ./lab:/lab
      - ./vtx:/vtx
      - ./ctx:/ctx
      # - ipfs:/ipfs
    env_file:
      - .env
    environment:
      FOCUS: heart
      TRANSFORMERS_CACHE: /tmp

  ctx:
    image: ghcr.io/0-5788719150923125/src:1
    command: nodemon --ext '*.js' --watch '/vtx/ctx' --exec npm start
    restart: 'always'
    volumes:
      - ./ctx:/vtx/ctx
      - ./vtx:/vtx/vtx
      - ./lab:/vtx/lab
      # - ipfs:/ipfs
    ports:
      - 9666:9666

  pet:
    image: learningathome/petals:main
    command: python -m petals.cli.run_server bigscience/bloom-7b1-petals --cache_dir /pet --num_blocks 1 --torch_dtype float32 --throughput 1
    restart: 'no'
    network_mode: 'host'
    ipc: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M
    volumes:
      - pet:/pet
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]

  pit:
    image: ghcr.io/0-5788719150923125/src:1
    command: tensorboard --logdir /gen/logs --bind_all --samples_per_plugin scalars=999999999
    volumes:
      - ./gen:/gen
    ports:
      - 6006:6006

  ship:
    image: tloncorp/urbit:v1.14
    command: /bin/urbit -t -c needle
    restart: 'always'
    # volumes:
    #   - comet:/urbit
    ports:
      - 9667:80
      - 34343:34343
#   ipfs:
#     image: ipfs/kubo:master-latest
#     command: daemon --mount --mount-ipfs=/ipfs --migrate=true --agent-version-suffix=docker --init-profile=lowpower --writable --enable-gc --enable-pubsub-experiment --enable-namesys-pubsub
#     restart: 'always'
#     build:
#       context: .
#       dockerfile: Dockerfile.ipfs
#     user: 1000:1000
#     privileged: true
#     devices:
#       - /dev/fuse:/dev/fuse
#     cap_add:
#       - SYS_ADMIN
#     volumes:
#       - ./vtx:/vtx
#       - ipfs:/ipfs
#       - ./001-test.sh:/container-init.d/001-test.sh
volumes:
  pet:
  # ipfs:
# comet:
# fuse:
