head:
  info: use your heads
  model: EleutherAI/gpt-neo-2.7B
  to_gpu: False

heart:
  info: never focus on the heart
  to_gpu: False
  n_gpu: 1
  training:
    base_model: EleutherAI/gpt-neo-125M
    vocab_size: 2048
    block_size: 256
    batch_size: 8
    gradient_accumulation_steps: 6
    num_steps: 5000

soul:
  version: 0
  info: bury your desires
  to_gpu: False
  n_gpu: 1
  training:
    base_model: xhyi/PT_GPTNEO350_ATG
    vocab_size: 4096
    block_size: 256
    batch_size: 1
    gradient_accumulation_steps: 32
    num_steps: 5000
    to_gpu: True

voice:
  version: 0
  info: never stop talking
  to_gpu: False
  n_gpu: 1
  training:
    base_model: xhyi/PT_GPTNEO350_ATG
    batch_size: 1
    block_size: 256
    num_steps: 20000
    warmup_steps: 500
    gradient_accumulation_steps: 24
    to_gpu: True
    learning_rate: 0.0012
    weight_decay: 0.06
    max_grad_norm: 0.6
    vocab_path: texts
    vocab_size: 4096
    dropout: 0.1
    equalize_datasets: True
    datasets:
      - folder: texts
      - folder: journals
      - folder: research
      - folder: discord
      - folder: reddit
        line_by_line: True

reddit:
  - sub: 5September2020
    skip: True
  - sub: radicalmentalhealth
    skip: True
  - sub: titor
    skip: True
  - sub: FrontLands
    skip: True
  - sub: NUVIEVA
    skip: True
  - sub: stairsofpantheon
  - sub: Kunism
  - sub: undersideof7threalm
  - sub: adanceoffeathers
  - sub: LegionOfReason
  - sub: TheFold
  - sub: TheSource
  - sub: TheInk

discord:
  all_dms: True
  servers:
    - id: '830300981966143488'
    - id: '896111349300592650'
    - id: '1041331166592106576'
    - id: '907925566089465886'
    - id: '747807102759731291'
    - id: '1047276906636132432'
    - id: '922565350598508664'
    - id: '829345498326106142'
    - id: '976908406864613436'
    - id: '840978732772753468'
    - id: '1042822599362752562'
    - id: '716611330198732868'
      after: '2022-09-05 12:34'
    - id: '860572485799379025'
