head:
  info: use your heads
  model: EleutherAI/gpt-neo-2.7B
  to_gpu: False

heart:
  version: 0
  info: never focus on the heart
  to_gpu: False
  n_gpu: 1
  training:
    base_model: EleutherAI/gpt-neo-125M
    vocab_size: 2048
    block_size: 256
    batch_size: 8
    gradient_accumulation_steps: 6
    num_steps: 5000

soul:
  version: 0
  info: bury your desires
  to_gpu: False
  n_gpu: 1
  training:
    base_model: xhyi/PT_GPTNEO350_ATG
    vocab_size: 4096
    block_size: 256
    batch_size: 1
    gradient_accumulation_steps: 32
    num_steps: 5000
    to_gpu: True

voice:
  version: 0
  info: never stop talking
  to_gpu: False
  n_gpu: 1
  training:
    base_model: xhyi/PT_GPTNEO350_ATG
    to_gpu: True
    batch_size: 1
    block_size: 333
    num_steps: 20000
    warmup_steps: 0
    gradient_accumulation_steps: 32
    learning_rate: 0.0013
    weight_decay: 0.06
    max_grad_norm: 0.4
    vocab_path: research
    vocab_size: 3333
    dropout: 0.1
    equalize_datasets: False
    datasets:
      - folder: research
      - folder: texts
      - folder: journals
      - folder: discord
      - folder: reddit
        line_by_line: True

reddit:
  - sub: 5September2020
    skip: True
  - sub: radicalmentalhealth
    skip: True
  - sub: titor
    skip: True
  - sub: FrontLands
    skip: True
  - sub: NUVIEVA
    skip: True
  - sub: stairsofpantheon
  - sub: Kunism
  - sub: undersideof7threalm
  - sub: adanceoffeathers
  - sub: LegionOfReason
  - sub: TheFold
  - sub: TheSource
  - sub: TheInk

discord:
  use_self_token: True
  export_dms: True
  servers:
    - id: '558378982920159242' # Rising Sun Society
      before: '2021-01-01 12:00'
      skip: True
    - id: '830300981966143488' # src
    - id: '896111349300592650' # The Vortex
    - id: '1041331166592106576' # The Brain
    - id: '907925566089465886' # Labyrinth
    - id: '747807102759731291' # Kunist's Server
    - id: '1047276906636132432' # The Underside of the 7th Realm
    - id: '922565350598508664' # BOTS FOR EVERYONE
    - id: '829345498326106142' # The Pantheon
    - id: '976908406864613436' # Darkwater Foundation
    - id: '840978732772753468' # The Cause
    - id: '1042822599362752562' # Lux Prima
