head:
  info: use your heads
  model: EleutherAI/gpt-neo-2.7B
  to_gpu: False

heart:
  info: never focus on the heart
  to_gpu: False
  n_gpu: 1
  training:
    base_model: EleutherAI/gpt-neo-125M
    vocab_size: 2048
    block_size: 256
    batch_size: 8
    gradient_accumulation_steps: 6
    num_steps: 5000

soul:
  info: bury your desires
  to_gpu: False
  n_gpu: 1
  training:
    base_model: xhyi/PT_GPTNEO350_ATG
    vocab_size: 4096
    block_size: 256
    batch_size: 1
    gradient_accumulation_steps: 32
    num_steps: 5000
    to_gpu: True

voice:
  info: never stop talking
  to_gpu: False
  n_gpu: 1
  training:
    base_model: xhyi/PT_GPTNEO350_ATG
    vocab_size: 4096
    batch_size: 2
    gradient_accumulation_steps: 16
    block_size: 512
    num_steps: 20000
    vocab_path: texts
    to_gpu: True
    equalize_datasets: True
    dropout: 0.1
    corpuses:
      - folder: journals
        line_by_line: False
      - folder: texts
        line_by_line: False
      - folder: research
        line_by_line: False
      - folder: discord
        line_by_line: False
      - folder: reddit
        line_by_line: False

reddit:
  - sub: 5September2020
    limit: 500
  - sub: stairsofpantheon
    limit: 500
  - sub: Kunism
    limit: 500
  - sub: undersideof7threalm
    limit: 500

discord:
  all_dms: True
  servers:
    - id: '830300981966143488'
    - id: '896111349300592650'
    - id: '1041331166592106576'
    - id: '907925566089465886'
    - id: '747807102759731291'
    - id: '1047276906636132432'
    - id: '922565350598508664'
    - id: '829345498326106142'
    - id: '976908406864613436'
    - id: '840978732772753468'
    - id: '1042822599362752562'
    - id: '716611330198732868'
      after: '2022-09-05 12:34'
    - id: '860572485799379025'
