source:
  hive:
    watch: True
    chance: 0.33

heart:
  info: never give up, never give in
  model: gpt2
  to_gpu: False

mind:
  info: use your heads
  model: EleutherAI/gpt-neo-1.3B
  to_gpu: False

soul:
  info: almost nobody has one
  to_gpu: True
  n_gpu: 1
  max_new_tokens: 333
  training:
    resume: True
    base_model: xhyi/PT_GPTNEO350_ATG
    to_gpu: 1
    batch_size: 2
    block_size: 111
    num_steps: 88888
    warmup_steps: 0
    gradient_accumulation_steps: 9
    learning_rate: 0.000666
    weight_decay: 0.023
    max_grad_norm: 0.444
    freeze_layers: True
    num_layers_freeze: 19
    equalize_datasets: False
    datasets:
      lab/aitextgen:
      lab/swarm:
      lab/source:
      lab/ink:
      lab/pen:
      lab/journals:
      lab/research:
      lab/theory:
      lab/pages:
      lab/texts:
      vtx:
      ctx:

toe:
  info: nailed to the foot
  to_gpu: False
  n_gpu: 1
  max_new_tokens: 333
  training:
    resume: True
    base_model: EleutherAI/gpt-neo-125M
    to_gpu: True
    batch_size: 3
    block_size: 444
    num_steps: 88888
    warmup_steps: 0
    gradient_accumulation_steps: 6
    learning_rate: 0.000666 # FOLD
    weight_decay: 0.023 # CORE
    max_grad_norm: 0.444 # ROOT
    freeze_layers: True
    num_layers_freeze: 9
    equalize_datasets: False
    datasets:
      lab/aitextgen:
      lab/swarm:
      lab/source:
      lab/ink:
      lab/pen:
      lab/journals:
      lab/research:
      lab/theory:
      lab/pages:
      lab/texts:
      vtx:
      ctx:

reddit:
  SubSimGPT2Interactive:
    limit: 10
    type: new
    skip: True
    watch: True
    chance: 0.001
  Kunism:
    limit: 500
    watch: True
    chance: 0.5

discord:
  use_self_token: True
  export_dms: True
  servers:
    '558378982920159242':
      before: '2021-01-01 12:00'
      skip: True
    '1041331166592106576':
    '907925566089465886':
