source:
  support:
    watch: True
    chance: 0.03

heart:
  info: never focus on the heart
  model: gpt2
  to_gpu: False

mind:
  info: use your heads
  model: EleutherAI/gpt-neo-1.3B
  to_gpu: False

soul:
  version: 0
  info: what drives us
  to_gpu: True
  n_gpu: 1
  training:
    base_model: xhyi/PT_GPTNEO350_ATG
    to_gpu: 1
    batch_size: 2
    block_size: 512
    num_steps: 20000
    warmup_steps: 0
    gradient_accumulation_steps: 16
    learning_rate: 0.000666
    weight_decay: 0.03
    max_grad_norm: 0.444
    freeze_layers: True
    num_layers_freeze: 12
    equalize_datasets: False
    datasets:
      lab/texts:
      lab/journals:
      lab/discord:
      lab/reddit:
        line_by_line: True

toe:
  version: 0
  info: never give up, never give in
  to_gpu: False
  n_gpu: 1
  max_new_tokens: 333
  training:
    resume: True
    base_model: EleutherAI/gpt-neo-125M
    to_gpu: True
    batch_size: 3
    block_size: 222
    num_steps: 88888
    warmup_steps: 0
    gradient_accumulation_steps: 3
    learning_rate: 0.000666 # FOLD
    weight_decay: 0.023 # CORE
    max_grad_norm: 0.444 # ROOT
    freeze_layers: True
    num_layers_freeze: 7
    equalize_datasets: False
    datasets:
      lab/aitextgen:
      lab/swarm:
      lab/source:
      lab/ink:
      lab/pen:
      lab/journals:
      lab/research:
      lab/theory:
      lab/pages:
      lab/texts:
      vtx:
      ctx:

reddit:
  SubSimGPT2Interactive:
    limit: 50
    skip: True
    watch: True
    chance: 0.1
  Kunism:
    limit: 500
    watch: True
    chance: 0.5

discord:
  use_self_token: True
  export_dms: True
  servers:
    '558378982920159242':
      before: '2021-01-01 12:00'
      skip: True
    '1041331166592106576':
    '907925566089465886':
