mode:
  test: False

source:
  support:
    watch: True

heart:
  info: never focus on the heart
  model: gpt2
  to_gpu: False

mind:
  info: use your heads
  model: EleutherAI/gpt-neo-1.3B
  to_gpu: False

soul:
  version: 0
  info: what drives us
  to_gpu: True
  n_gpu: 1
  training:
    base_model: xhyi/PT_GPTNEO350_ATG
    to_gpu: 1
    batch_size: 2
    block_size: 512
    num_steps: 20000
    warmup_steps: 0
    gradient_accumulation_steps: 16
    learning_rate: 0.000666
    weight_decay: 0.03
    max_grad_norm: 0.444
    freeze_layers: True
    num_layers_freeze: 12
    equalize_datasets: False
    datasets:
      texts:
      journals:
      discord:
      reddit:
        line_by_line: True

toe:
  version: 0
  info: never give up, never give in
  to_gpu: False
  n_gpu: 1
  max_length: 666
  training:
    base_model: EleutherAI/gpt-neo-125M
    to_gpu: 1
    batch_size: 1
    block_size: 222
    num_steps: 99999
    warmup_steps: 0
    gradient_accumulation_steps: 11
    learning_rate: 0.000666 # CORE
    weight_decay: 0.4444 # ROOT
    max_grad_norm: 0.333 # FOLD
    freeze_layers: True
    num_layers_freeze: 7
    equalize_datasets: False
    datasets:
      journals:
      pages:
      texts:
      discord:
      reddit:
        line_by_line: True

reddit:
  SubSimGPT2Interactive:
    limit: 50
    skip: True
    watch: True
    chance: 1
  Kunism:
    limit: 500
    watch: True
    chance: 100

discord:
  use_self_token: True
  export_dms: True
  servers:
    '558378982920159242':
      before: '2021-01-01 12:00'
      skip: True
    '1041331166592106576':
    '907925566089465886':
