version: '3.9'

services:
  bot:
    image: ghcr.io/0-5788719150923125/bot:latest
    stdin_open: true
    tty: true
    volumes:
      - ./config.yml:/src/config.yml
      - ./models:/src/models
    env_file:
      - .env

  ctx:
    image: ghcr.io/0-5788719150923125/src:latest
    restart: 'always'
    logging:
      driver: none
    ports:
      - 9666:9666
    environment:
      WEBUI: enabled