version: '3.9'

services:
  bot:
    image: ghcr.io/0-5788719150923125/bot:latest
    command: nodemon --ext '*.py, *.yml' --ignore "models/*" --ignore "*.json" --exec python3 /src/main.py
    restart: 'always'
    stdin_open: true
    tty: true
    volumes:
      - ./config.yml:/src/config.yml
      - ./models:/src/models
    env_file:
      - .env
    environment:
      FOCUS: mind
      TRANSFORMERS_CACHE: /tmp

  ctx:
    image: ghcr.io/0-5788719150923125/src:latest
    restart: 'always'
    logging:
      driver: none
    ports:
      - 9666:9666
    environment:
      WEBUI: disabled
      ANONYMOUS: 'true'