mode:
  test: False

reddit:
  SubSimGPT2Interactive:
    skip: True
    chance: 22
  5September2020:
    skip: False
  radicalmentalhealth:
    skip: False
    limit: 50
    chance: 11
    watch: True
  titor:
    skip: True
  FrontLands:
    skip: True
    watch: True
  NUVIEVA:
    skip: True
    watch: True
  stairsofpantheon:
    limit: 500
    watch: True
  Kunism:
    limit: 500
    watch: True
  undersideof7threalm:
    limit: 500
    watch: True
  adanceoffeathers:
    limit: 500
    skip: True
    watch: True
  LegionOfReason:
    limit: 500
    watch: True
  TheFold:
    limit: 500
    watch: True
  TheSource:
    limit: 500
    watch: True
  TheInk:
    limit: 500
    watch: True

discord:
  use_self_token: True
  export_dms: True
  servers:
    '558378982920159242': # Rising Sun Society
      before: '2021-01-01 12:00'
      skip: True
    '830300981966143488': # src
    '896111349300592650': # The Vortex
    '1041331166592106576': # The Brain
    '907925566089465886': # Labyrinth
    '747807102759731291': # Kunist's Server
    '1047276906636132432': # The Underside of the 7th Realm
    '922565350598508664': # BOTS FOR EVERYONE
    '829345498326106142': # The Pantheon
    '976908406864613436': # Darkwater Foundation
    '840978732772753468': # The Cause
    '1042822599362752562': # Lux Prima
    '386853267058982912': # Toehider

twitter:
