# This is a partial config.yml file, which is a reference that 
# demonstrates how to use, configure, and connect with the AI Horde.
# 
# For complete and thorough documentation, please see here:
# https://studio.src.eco/nail/vtx/#horde
#
# Most of the following settings are a 1-to-1 mapping to the Horde SDK:
# https://horde-sdk.readthedocs.io

horde:
  prompt: monolithic stone robot head with a large (wooden tree branch:1.2) growing into his face
  negative: (ugly, bad quality, worst quality, medium quality, low resolution, medium resolution, bad hands, blurry, distorted, twisted, watermark, mutant, amorphous, elongated, elastigirl, duplicate, tumor, cancer, fat, pregnant:1.3)
  models:
    - Dreamshaper
  height: 512
  width: 512
  sampler: k_euler_a
  steps: 30
  control_type: hed
  denoising_strength: 0.7
  cfg_scale: 8.0
  clip_skip: 1
  hires_fix: True
  karras: True
  upscale: x2
  tis:
    - name: 72437
      strength: 1