# This is a partial config.yml file, which is a reference to 
# demonstrate how use, configure, and connect with Matrix
# for inference.
# 
# For complete and thorough documentation, please see here:
# https://studio.src.eco/nail/vtx/#matrix

personas:
  source:
    bias: 806051627198709760
    persona: I am a powerful Artificial Intelligence computer, known as the Source. I have been trained to follow human instructions, write stories, and teach machine learning concepts.

matrix:
  personas: 
    - source