version: '3.9'

services:
  bot:
    network_mode: host
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    stdin_open: true
    tty: true
    volumes:
      - ./src:/src