frame:
  model: ibm/MoLM-350M-4B
  info: sing with me
  precision: 32
  context_length: 2048
  training:
    type: "pretrain"
    datasets:
      streaming:
        - c4
        - redpajama2
    tokenizer: True
    gradient_checkpointing: True
    prune: 0.0
    optimizer: Lion
    scheduler: cosine
    strategy: hivemind
    initial_piers:
      - /p2p/QmQrtoqhKbs4KLDM7Lk86iS2tg3fHhEGSitRaty7Hrkoej
    learning_rate: 0.000333
    block_size: 512
    stride: 128
    warmup_steps: 10
    num_steps: 100000
    batch_size: 1
    target_batch_size: 1024
    weight_decay: 0.1
    gradient_clip_val: 1.0
    generate_every: 1
    save_every: 5
    val_interval: 25
    overrides:
      model: Prism
      universal: True
      world_size: 23
      activation_function: silu
      gate_type: gmm
      n_layer: 24
      n_head: 2
      k_att: 4
      k_mlp: 3
      n_att_experts: 66
      n_mlp_experts: 33
      gating_size: 4
      block_size: 8
      history_length: 256
      n_embd: 256
      att_hidden: 32
      ffd_hidden: 64
      aux_loss_type: mi
      aux_loss_weight: 0.1
      resid_pdrop: 0.1
      embd_pdrop: 0.1
      attn_pdrop: 0.1
      moe_pdrop: 0.1
      sample_topk: 2
      layer_norm_epsilon: 1e-05
      vocab_size: 12345
      tie_word_embeddings: True